# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

package:
  name: ros-jazzy-rosidl-generator-py
  version: 0.22.0
source:
  git: https://github.com/ros2-gbp/rosidl_python-release.git
  rev: release/jazzy/rosidl_generator_py/0.22.0-2
  target_directory: ros-jazzy-rosidl-generator-py/src/work

build:
  script: ${{ 'build_ament_cmake.sh' if unix else 'bld_ament_cmake.bat' }}
  number: 0
  post_process:
    - files:
        - '*.pc'
      regex: (?:-L|-I)?"?([^;\s]+/sysroot/)
      replacement: $(CONDA_BUILD_SYSROOT_S)
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/sysroot)
      replacement: $ENV{CONDA_BUILD_SYSROOT}
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/MacOSX\d*\.?\d*\.sdk)
      replacement: $ENV{CONDA_BUILD_SYSROOT}
about:
  homepage: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ninja
    - setuptools
    - if: unix
      then:
        - make
        - coreutils
    - if: osx
      then:
        - tapi
    - if: build_platform != target_platform
      then:
        - pkg-config
    - cmake
    - cython
    - if: build_platform != target_platform
      then:
        - python
    - if: build_platform != target_platform
      then:
        - cross-python_${{ target_platform }}
    - if: build_platform != target_platform
      then:
        - numpy
  host:
    - if: build_platform == target_platform
      then:
        - pkg-config
    - numpy
    - pip
    - pytest
    - python
    - ros-jazzy-ament-cmake
    - ros-jazzy-ament-cmake-pytest
    - ros-jazzy-ament-index-python
    - ros-jazzy-ament-lint-auto
    - ros-jazzy-ament-lint-common
    - ros-jazzy-python-cmake-module
    - ros-jazzy-rmw
    - ros-jazzy-ros-environment
    - ros-jazzy-ros-workspace
    - ros-jazzy-rosidl-cmake
    - ros-jazzy-rosidl-generator-c
    - ros-jazzy-rosidl-generator-cpp
    - ros-jazzy-rosidl-parser
    - ros-jazzy-rosidl-pycommon
    - ros-jazzy-rosidl-runtime-c
    - ros-jazzy-rosidl-typesupport-c
    - ros-jazzy-rosidl-typesupport-fastrtps-c
    - ros-jazzy-rosidl-typesupport-interface
    - ros-jazzy-rosidl-typesupport-introspection-c
    - ros-jazzy-rpyutils
    - ros-jazzy-test-interface-files
    - ros2-distro-mutex 0.5 jazzy
  run:
    - numpy
    - python
    - ros-jazzy-ament-cmake
    - ros-jazzy-ament-cmake-cppcheck
    - ros-jazzy-ament-cmake-cpplint
    - ros-jazzy-ament-cmake-flake8
    - ros-jazzy-ament-cmake-pep257
    - ros-jazzy-ament-cmake-uncrustify
    - ros-jazzy-ament-index-python
    - ros-jazzy-python-cmake-module
    - ros-jazzy-rmw
    - ros-jazzy-ros-workspace
    - ros-jazzy-rosidl-cli
    - ros-jazzy-rosidl-generator-c
    - ros-jazzy-rosidl-parser
    - ros-jazzy-rosidl-pycommon
    - ros-jazzy-rosidl-runtime-c
    - ros-jazzy-rosidl-typesupport-c
    - ros-jazzy-rosidl-typesupport-interface
    - ros-jazzy-rpyutils
    - ros2-distro-mutex 0.5 jazzy
    - if: osx and x86_64
      then:
        - __osx >=${{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
