# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

package:
  name: ros-jazzy-ros-core
  version: 0.11.0
source:
  git: https://github.com/ros2-gbp/variants-release.git
  rev: release/jazzy/ros_core/0.11.0-1
  target_directory: ros-jazzy-ros-core/src/work

build:
  script: ${{ 'build_ament_cmake.sh' if unix else 'bld_ament_cmake.bat' }}
  number: 0
  post_process:
    - files:
        - '*.pc'
      regex: (?:-L|-I)?"?([^;\s]+/sysroot/)
      replacement: $(CONDA_BUILD_SYSROOT_S)
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/sysroot)
      replacement: $ENV{CONDA_BUILD_SYSROOT}
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/MacOSX\d*\.?\d*\.sdk)
      replacement: $ENV{CONDA_BUILD_SYSROOT}
about:
  homepage: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ninja
    - setuptools
    - if: unix
      then:
        - make
        - coreutils
    - if: osx
      then:
        - tapi
    - if: build_platform != target_platform
      then:
        - pkg-config
    - cmake
    - cython
    - if: build_platform != target_platform
      then:
        - python
    - if: build_platform != target_platform
      then:
        - cross-python_${{ target_platform }}
    - if: build_platform != target_platform
      then:
        - numpy
  host:
    - if: build_platform == target_platform
      then:
        - pkg-config
    - numpy
    - pip
    - python
    - ros-jazzy-ament-cmake
    - ros-jazzy-ros-environment
    - ros-jazzy-ros-workspace
    - ros2-distro-mutex 0.5 jazzy
  run:
    - python
    - ros-jazzy-ament-cmake
    - ros-jazzy-ament-cmake-auto
    - ros-jazzy-ament-cmake-gmock
    - ros-jazzy-ament-cmake-gtest
    - ros-jazzy-ament-cmake-pytest
    - ros-jazzy-ament-cmake-ros
    - ros-jazzy-ament-index-cpp
    - ros-jazzy-ament-index-python
    - ros-jazzy-ament-lint-auto
    - ros-jazzy-ament-lint-common
    - ros-jazzy-class-loader
    - ros-jazzy-common-interfaces
    - ros-jazzy-launch
    - ros-jazzy-launch-ros
    - ros-jazzy-launch-testing
    - ros-jazzy-launch-testing-ament-cmake
    - ros-jazzy-launch-testing-ros
    - ros-jazzy-launch-xml
    - ros-jazzy-launch-yaml
    - ros-jazzy-pluginlib
    - ros-jazzy-rcl-lifecycle
    - ros-jazzy-rclcpp
    - ros-jazzy-rclcpp-action
    - ros-jazzy-rclcpp-lifecycle
    - ros-jazzy-rclpy
    - ros-jazzy-ros-environment
    - ros-jazzy-ros-workspace
    - ros-jazzy-ros2cli-common-extensions
    - ros-jazzy-ros2launch
    - ros-jazzy-rosidl-default-generators
    - ros-jazzy-rosidl-default-runtime
    - ros-jazzy-sros2
    - ros-jazzy-sros2-cmake
    - ros2-distro-mutex 0.5 jazzy
    - if: osx and x86_64
      then:
        - __osx >=${{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
