# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

package:
  name: ros-jazzy-rcl
  version: 9.2.3
source:
  git: https://github.com/ros2-gbp/rcl-release.git
  rev: release/jazzy/rcl/9.2.3-1
  target_directory: ros-jazzy-rcl/src/work

build:
  script: ${{ 'build_ament_cmake.sh' if unix else 'bld_ament_cmake.bat' }}
  number: 0
  post_process:
    - files:
        - '*.pc'
      regex: (?:-L|-I)?"?([^;\s]+/sysroot/)
      replacement: $(CONDA_BUILD_SYSROOT_S)
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/sysroot)
      replacement: $ENV{CONDA_BUILD_SYSROOT}
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/MacOSX\d*\.?\d*\.sdk)
      replacement: $ENV{CONDA_BUILD_SYSROOT}
about:
  homepage: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ninja
    - setuptools
    - if: unix
      then:
        - make
        - coreutils
    - if: osx
      then:
        - tapi
    - if: build_platform != target_platform
      then:
        - pkg-config
    - cmake
    - cython
    - if: build_platform != target_platform
      then:
        - python
    - if: build_platform != target_platform
      then:
        - cross-python_${{ target_platform }}
    - if: build_platform != target_platform
      then:
        - numpy
  host:
    - if: build_platform == target_platform
      then:
        - pkg-config
    - numpy
    - pip
    - python
    - ros-jazzy-ament-cmake-gen-version-h
    - ros-jazzy-ament-cmake-gtest
    - ros-jazzy-ament-cmake-ros
    - ros-jazzy-ament-lint-auto
    - ros-jazzy-ament-lint-common
    - ros-jazzy-launch
    - ros-jazzy-launch-testing
    - ros-jazzy-launch-testing-ament-cmake
    - ros-jazzy-libyaml-vendor
    - ros-jazzy-mimick-vendor
    - ros-jazzy-osrf-testing-tools-cpp
    - ros-jazzy-rcl-interfaces
    - ros-jazzy-rcl-logging-interface
    - ros-jazzy-rcl-logging-spdlog
    - ros-jazzy-rcl-yaml-param-parser
    - ros-jazzy-rcutils
    - ros-jazzy-rmw
    - ros-jazzy-rmw-implementation
    - ros-jazzy-rmw-implementation-cmake
    - ros-jazzy-ros-environment
    - ros-jazzy-ros-workspace
    - ros-jazzy-rosidl-runtime-c
    - ros-jazzy-rosidl-runtime-cpp
    - ros-jazzy-service-msgs
    - ros-jazzy-test-msgs
    - ros-jazzy-tracetools
    - ros-jazzy-type-description-interfaces
    - ros2-distro-mutex 0.5 jazzy
    - yaml
    - yaml-cpp
  run:
    - python
    - ros-jazzy-libyaml-vendor
    - ros-jazzy-rcl-interfaces
    - ros-jazzy-rcl-logging-interface
    - ros-jazzy-rcl-logging-spdlog
    - ros-jazzy-rcl-yaml-param-parser
    - ros-jazzy-rcutils
    - ros-jazzy-rmw
    - ros-jazzy-rmw-implementation
    - ros-jazzy-ros-workspace
    - ros-jazzy-rosidl-runtime-c
    - ros-jazzy-service-msgs
    - ros-jazzy-tracetools
    - ros-jazzy-type-description-interfaces
    - ros2-distro-mutex 0.5 jazzy
    - yaml
    - yaml-cpp
    - if: osx and x86_64
      then:
        - __osx >=${{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
